"""initial

Revision ID: 89089f1187c9
Revises: 
Create Date: 2026-01-17 21:27:57.562666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89089f1187c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY', name='badgerarity'), nullable=False),
    sa.Column('category', sa.Enum('PROBLEM_SOLVING', 'STREAK', 'MASTERY', 'SOCIAL', 'SPECIAL', name='badgecategory'), nullable=False),
    sa.Column('requirement', sa.String(length=100), nullable=False),
    sa.Column('requirement_value', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badges')),
    sa.UniqueConstraint('name', name=op.f('uq_badges_name'))
    )
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('challenge_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'SPECIAL', name='challengetype'), nullable=False),
    sa.Column('target_action', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    op.create_table('code_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_templates'))
    )
    op.create_index(op.f('ix_code_templates_category'), 'code_templates', ['category'], unique=False)
    op.create_index(op.f('ix_code_templates_language'), 'code_templates', ['language'], unique=False)
    op.create_index('ix_templates_category_usage', 'code_templates', ['category', 'usage_count'], unique=False)
    op.create_table('learning_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_paths'))
    )
    op.create_table('model_training_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('training_started_at', sa.DateTime(), nullable=False),
    sa.Column('training_completed_at', sa.DateTime(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('epochs_completed', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_training_logs'))
    )
    op.create_index(op.f('ix_model_training_logs_model_type'), 'model_training_logs', ['model_type'], unique=False)
    op.create_index('ix_model_training_type_active', 'model_training_logs', ['model_type', 'is_active'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('category', sa.Enum('ARRAY', 'STRING', 'LINKED_LIST', 'STACK', 'QUEUE', 'HASH_TABLE', 'HEAP', 'TREE', 'GRAPH', 'SORTING', 'SEARCHING', 'DYNAMIC_PROGRAMMING', 'GREEDY', 'BACKTRACKING', 'RECURSION', 'TWO_POINTERS', 'SLIDING_WINDOW', 'BINARY_SEARCH', 'BFS', 'DFS', 'DIVIDE_AND_CONQUER', 'DESIGN', 'MATH', 'SIMULATION', name='category'), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=False),
    sa.Column('hints', sa.JSON(), nullable=False),
    sa.Column('solution_template', sa.Text(), nullable=False),
    sa.Column('reference_solution', sa.Text(), nullable=False),
    sa.Column('time_limit_ms', sa.Integer(), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('pattern_ids', sa.JSON(), nullable=False),
    sa.Column('pattern_explanation', sa.Text(), nullable=False),
    sa.Column('approach_hint', sa.Text(), nullable=False),
    sa.Column('time_complexity_hint', sa.String(length=50), nullable=False),
    sa.Column('space_complexity_hint', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    op.create_index(op.f('ix_problems_category'), 'problems', ['category'], unique=False)
    op.create_index(op.f('ix_problems_is_published'), 'problems', ['is_published'], unique=False)
    op.create_table('typing_exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_completions', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_typing_exercises'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('collaboration_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=True),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('code_content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('fk_collaboration_sessions_host_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_collaboration_sessions_problem_id_problems'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaboration_sessions'))
    )
    op.create_index('ix_collab_sessions_status_created', 'collaboration_sessions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_collaboration_sessions_host_id'), 'collaboration_sessions', ['host_id'], unique=False)
    op.create_index(op.f('ix_collaboration_sessions_problem_id'), 'collaboration_sessions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_collaboration_sessions_status'), 'collaboration_sessions', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_type', sa.Enum('GENERAL', 'PROBLEM_HELP', 'CODE_REVIEW', 'CONCEPT', name='conversationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_conversations_problem_id_problems'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_is_active'), 'conversations', ['is_active'], unique=False)
    op.create_index(op.f('ix_conversations_problem_id'), 'conversations', ['problem_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stats_date', sa.Date(), nullable=False),
    sa.Column('problems_attempted', sa.Integer(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('avg_time_to_solve_ms', sa.Float(), nullable=False),
    sa.Column('avg_memory_usage_mb', sa.Float(), nullable=False),
    sa.Column('easy_solved', sa.Integer(), nullable=False),
    sa.Column('medium_solved', sa.Integer(), nullable=False),
    sa.Column('hard_solved', sa.Integer(), nullable=False),
    sa.Column('categories_attempted', sa.Integer(), nullable=False),
    sa.Column('category_breakdown', sa.JSON(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('study_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active_day', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_stats')),
    sa.UniqueConstraint('user_id', 'stats_date', name='uq_daily_stats_user_date')
    )
    op.create_index(op.f('ix_daily_stats_stats_date'), 'daily_stats', ['stats_date'], unique=False)
    op.create_index('ix_daily_stats_user_date', 'daily_stats', ['user_id', 'stats_date'], unique=False)
    op.create_index(op.f('ix_daily_stats_user_id'), 'daily_stats', ['user_id'], unique=False)
    op.create_table('path_prerequisites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('prerequisite_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], name=op.f('fk_path_prerequisites_path_id_learning_paths')),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['learning_paths.id'], name=op.f('fk_path_prerequisites_prerequisite_id_learning_paths')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_path_prerequisites'))
    )
    op.create_table('playgrounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('share_code', sa.String(length=32), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=False),
    sa.Column('is_forked', sa.Boolean(), nullable=False),
    sa.Column('forked_from_id', sa.Uuid(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('fork_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_id'], ['playgrounds.id'], name=op.f('fk_playgrounds_forked_from_id_playgrounds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_playgrounds_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playgrounds'))
    )
    op.create_index(op.f('ix_playgrounds_owner_id'), 'playgrounds', ['owner_id'], unique=False)
    op.create_index('ix_playgrounds_owner_updated', 'playgrounds', ['owner_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_playgrounds_share_code'), 'playgrounds', ['share_code'], unique=True)
    op.create_index(op.f('ix_playgrounds_visibility'), 'playgrounds', ['visibility'], unique=False)
    op.create_index('ix_playgrounds_visibility_created', 'playgrounds', ['visibility', 'created_at'], unique=False)
    op.create_table('quality_trends',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trend_date', sa.Date(), nullable=False),
    sa.Column('avg_overall_score', sa.Float(), nullable=False),
    sa.Column('avg_correctness', sa.Float(), nullable=False),
    sa.Column('avg_efficiency', sa.Float(), nullable=False),
    sa.Column('avg_readability', sa.Float(), nullable=False),
    sa.Column('avg_best_practices', sa.Float(), nullable=False),
    sa.Column('avg_cyclomatic', sa.Float(), nullable=False),
    sa.Column('avg_cognitive', sa.Float(), nullable=False),
    sa.Column('submissions_analyzed', sa.Integer(), nullable=False),
    sa.Column('total_smells', sa.Integer(), nullable=False),
    sa.Column('total_suggestions', sa.Integer(), nullable=False),
    sa.Column('improved_count', sa.Integer(), nullable=False),
    sa.Column('grade_distribution', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quality_trends_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_trends')),
    sa.UniqueConstraint('user_id', 'trend_date', name='uq_quality_trends_user_date')
    )
    op.create_index(op.f('ix_quality_trends_trend_date'), 'quality_trends', ['trend_date'], unique=False)
    op.create_index('ix_quality_trends_user_date', 'quality_trends', ['user_id', 'trend_date'], unique=False)
    op.create_index(op.f('ix_quality_trends_user_id'), 'quality_trends', ['user_id'], unique=False)
    op.create_table('roadmap_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], name=op.f('fk_roadmap_modules_path_id_learning_paths')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_modules'))
    )
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILATION_ERROR', name='submissionstatus'), nullable=False),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('memory_usage_mb', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_submissions_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_index(op.f('ix_submissions_problem_id'), 'submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_submitted_at'), 'submissions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_test_cases_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_cases'))
    )
    op.create_index(op.f('ix_test_cases_problem_id'), 'test_cases', ['problem_id'], unique=False)
    op.create_table('typing_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('user_code', sa.Text(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('wpm', sa.Float(), nullable=True),
    sa.Column('time_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['typing_exercises.id'], name=op.f('fk_typing_attempts_exercise_id_typing_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_typing_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_typing_attempts'))
    )
    op.create_table('user_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], name=op.f('fk_user_badges_badge_id_badges')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_badges_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_badges'))
    )
    op.create_table('user_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', name='challengestatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_user_challenges_challenge_id_challenges')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_challenges_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_challenges'))
    )
    op.create_table('user_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('best_execution_time_ms', sa.Float(), nullable=True),
    sa.Column('best_memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('first_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('time_to_solve_seconds', sa.Integer(), nullable=True),
    sa.Column('interaction_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_user_interactions_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_interactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_interactions')),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_interactions_user_problem')
    )
    op.create_index(op.f('ix_user_interactions_problem_id'), 'user_interactions', ['problem_id'], unique=False)
    op.create_index('ix_user_interactions_solved', 'user_interactions', ['is_solved'], unique=False)
    op.create_index(op.f('ix_user_interactions_user_id'), 'user_interactions', ['user_id'], unique=False)
    op.create_index('ix_user_interactions_user_problem', 'user_interactions', ['user_id', 'problem_id'], unique=False)
    op.create_table('user_path_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_lessons', sa.Integer(), nullable=True),
    sa.Column('total_lessons', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], name=op.f('fk_user_path_progress_path_id_learning_paths')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_path_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_path_progress'))
    )
    op.create_table('user_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('problems_solved', sa.Integer(), nullable=True),
    sa.Column('problems_solved_first_try', sa.Integer(), nullable=True),
    sa.Column('patterns_mastered', sa.Integer(), nullable=True),
    sa.Column('collaborations_count', sa.Integer(), nullable=True),
    sa.Column('playgrounds_created', sa.Integer(), nullable=True),
    sa.Column('playgrounds_shared', sa.Integer(), nullable=True),
    sa.Column('lessons_completed', sa.Integer(), nullable=True),
    sa.Column('paths_completed', sa.Integer(), nullable=True),
    sa.Column('beginner_path_completed', sa.Boolean(), nullable=True),
    sa.Column('elementary_path_completed', sa.Boolean(), nullable=True),
    sa.Column('intermediate_path_completed', sa.Boolean(), nullable=True),
    sa.Column('advanced_path_completed', sa.Boolean(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_stats_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_stats')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_stats_user_id'))
    )
    op.create_table('code_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['collaboration_sessions.id'], name=op.f('fk_code_changes_session_id_collaboration_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_code_changes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_changes'))
    )
    op.create_index(op.f('ix_code_changes_session_id'), 'code_changes', ['session_id'], unique=False)
    op.create_index('ix_code_changes_session_version', 'code_changes', ['session_id', 'version'], unique=False)
    op.create_table('code_quality_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('correctness_score', sa.Integer(), nullable=False),
    sa.Column('efficiency_score', sa.Integer(), nullable=False),
    sa.Column('readability_score', sa.Integer(), nullable=False),
    sa.Column('best_practices_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('overall_grade', sa.String(length=2), nullable=False),
    sa.Column('code_smells', sa.JSON(), nullable=False),
    sa.Column('code_smells_count', sa.Integer(), nullable=False),
    sa.Column('cyclomatic_complexity', sa.Integer(), nullable=False),
    sa.Column('cognitive_complexity', sa.Integer(), nullable=False),
    sa.Column('max_nesting_depth', sa.Integer(), nullable=False),
    sa.Column('lines_of_code', sa.Integer(), nullable=False),
    sa.Column('detected_patterns', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('suggestions_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('analyzer_version', sa.String(length=20), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_code_quality_analyses_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_code_quality_analyses_submission_id_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_code_quality_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_quality_analyses'))
    )
    op.create_index(op.f('ix_code_quality_analyses_problem_id'), 'code_quality_analyses', ['problem_id'], unique=False)
    op.create_index(op.f('ix_code_quality_analyses_submission_id'), 'code_quality_analyses', ['submission_id'], unique=True)
    op.create_index(op.f('ix_code_quality_analyses_user_id'), 'code_quality_analyses', ['user_id'], unique=False)
    op.create_index('ix_quality_overall_score', 'code_quality_analyses', ['overall_score'], unique=False)
    op.create_index('ix_quality_problem', 'code_quality_analyses', ['problem_id'], unique=False)
    op.create_index('ix_quality_user_analyzed', 'code_quality_analyses', ['user_id', 'analyzed_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('code_context', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('playground_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('playground_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playground_id'], ['playgrounds.id'], name=op.f('fk_playground_executions_playground_id_playgrounds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_playground_executions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playground_executions'))
    )
    op.create_index('ix_executions_playground_time', 'playground_executions', ['playground_id', 'executed_at'], unique=False)
    op.create_index(op.f('ix_playground_executions_playground_id'), 'playground_executions', ['playground_id'], unique=False)
    op.create_index(op.f('ix_playground_executions_user_id'), 'playground_executions', ['user_id'], unique=False)
    op.create_table('roadmap_lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lesson_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_id', sa.String(length=36), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['roadmap_modules.id'], name=op.f('fk_roadmap_lessons_module_id_roadmap_modules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_lessons'))
    )
    op.create_table('session_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('cursor_position', sa.JSON(), nullable=True),
    sa.Column('selection_range', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['collaboration_sessions.id'], name=op.f('fk_session_participants_session_id_collaboration_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_participants'))
    )
    op.create_index('ix_participants_session_active', 'session_participants', ['session_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_session_participants_session_id'), 'session_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_participants_user_id'), 'session_participants', ['user_id'], unique=False)
    op.create_table('user_lesson_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['roadmap_lessons.id'], name=op.f('fk_user_lesson_progress_lesson_id_roadmap_lessons')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_lesson_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_lesson_progress'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lesson_progress')
    op.drop_index(op.f('ix_session_participants_user_id'), table_name='session_participants')
    op.drop_index(op.f('ix_session_participants_session_id'), table_name='session_participants')
    op.drop_index('ix_participants_session_active', table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_table('roadmap_lessons')
    op.drop_index(op.f('ix_playground_executions_user_id'), table_name='playground_executions')
    op.drop_index(op.f('ix_playground_executions_playground_id'), table_name='playground_executions')
    op.drop_index('ix_executions_playground_time', table_name='playground_executions')
    op.drop_table('playground_executions')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_quality_user_analyzed', table_name='code_quality_analyses')
    op.drop_index('ix_quality_problem', table_name='code_quality_analyses')
    op.drop_index('ix_quality_overall_score', table_name='code_quality_analyses')
    op.drop_index(op.f('ix_code_quality_analyses_user_id'), table_name='code_quality_analyses')
    op.drop_index(op.f('ix_code_quality_analyses_submission_id'), table_name='code_quality_analyses')
    op.drop_index(op.f('ix_code_quality_analyses_problem_id'), table_name='code_quality_analyses')
    op.drop_table('code_quality_analyses')
    op.drop_index('ix_code_changes_session_version', table_name='code_changes')
    op.drop_index(op.f('ix_code_changes_session_id'), table_name='code_changes')
    op.drop_table('code_changes')
    op.drop_table('user_stats')
    op.drop_table('user_path_progress')
    op.drop_index('ix_user_interactions_user_problem', table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_user_id'), table_name='user_interactions')
    op.drop_index('ix_user_interactions_solved', table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_problem_id'), table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_table('user_challenges')
    op.drop_table('user_badges')
    op.drop_table('typing_attempts')
    op.drop_index(op.f('ix_test_cases_problem_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_submitted_at'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_problem_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('roadmap_modules')
    op.drop_index(op.f('ix_quality_trends_user_id'), table_name='quality_trends')
    op.drop_index('ix_quality_trends_user_date', table_name='quality_trends')
    op.drop_index(op.f('ix_quality_trends_trend_date'), table_name='quality_trends')
    op.drop_table('quality_trends')
    op.drop_index('ix_playgrounds_visibility_created', table_name='playgrounds')
    op.drop_index(op.f('ix_playgrounds_visibility'), table_name='playgrounds')
    op.drop_index(op.f('ix_playgrounds_share_code'), table_name='playgrounds')
    op.drop_index('ix_playgrounds_owner_updated', table_name='playgrounds')
    op.drop_index(op.f('ix_playgrounds_owner_id'), table_name='playgrounds')
    op.drop_table('playgrounds')
    op.drop_table('path_prerequisites')
    op.drop_index(op.f('ix_daily_stats_user_id'), table_name='daily_stats')
    op.drop_index('ix_daily_stats_user_date', table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_stats_date'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_problem_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_active'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_collaboration_sessions_status'), table_name='collaboration_sessions')
    op.drop_index(op.f('ix_collaboration_sessions_problem_id'), table_name='collaboration_sessions')
    op.drop_index(op.f('ix_collaboration_sessions_host_id'), table_name='collaboration_sessions')
    op.drop_index('ix_collab_sessions_status_created', table_name='collaboration_sessions')
    op.drop_table('collaboration_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('typing_exercises')
    op.drop_index(op.f('ix_problems_is_published'), table_name='problems')
    op.drop_index(op.f('ix_problems_category'), table_name='problems')
    op.drop_table('problems')
    op.drop_index('ix_model_training_type_active', table_name='model_training_logs')
    op.drop_index(op.f('ix_model_training_logs_model_type'), table_name='model_training_logs')
    op.drop_table('model_training_logs')
    op.drop_table('learning_paths')
    op.drop_index('ix_templates_category_usage', table_name='code_templates')
    op.drop_index(op.f('ix_code_templates_language'), table_name='code_templates')
    op.drop_index(op.f('ix_code_templates_category'), table_name='code_templates')
    op.drop_table('code_templates')
    op.drop_table('challenges')
    op.drop_table('badges')
    # ### end Alembic commands ###
